export const transformPrompts = [
  // Visual Styles & Effects
  "Add dramatic lighting and shadows",
  "Make it look like a movie poster",
  "Apply vintage film aesthetic",
  "Add glowing neon effects",
  "Create a comic book art style",
  "Make it look professional and polished",
  "Add artistic blur and depth of field",
  "Apply watercolor painting effect",
  "Turn it into pixel art",
  "Add Renaissance oil painting style",
  "Make it look like a pencil sketch",
  "Apply cyberpunk aesthetic with neon accents",
  "Create an ink wash painting style",
  "Add vaporwave aesthetics",
  "Make it look like a Polaroid photo",
  "Apply holographic iridescent effects",
  "Turn it into stained glass art",
  "Add retro 80s VHS aesthetic",
  "Make it look like graffiti street art",
  "Apply bokeh effect with fairy lights",

  // Creative Transformations
  "Add an interesting background element",
  "Place the subject in a different environment",
  "Create a minimalist, clean version",
  "Transform into meme format with text",
  "Make it YouTube thumbnail ready",
  "Deep fry with oversaturated effects",
  "Add floating objects around the scene",
  "Replace the background with outer space",
  "Make it look like it's underwater",
  "Add mirror reflection effects",
  "Transform into a magazine cover",
  "Make it look like album cover art",
  "Add magical sparkles and fairy dust",
  "Place it on a billboard in Times Square",
  "Turn the subject into a cartoon character",
  "Add pop art style with bold colors",
  "Make it look like ancient cave art",
  "Transform into a tarot card design",
  "Add surreal melting effect",
  "Make it look like a concert poster",

  // Mood & Atmosphere
  "Make it feel more dramatic and intense",
  "Add a cozy, warm atmosphere",
  "Create a futuristic sci-fi vibe",
  "Make it look mysterious and moody",
  "Add energy and motion to the scene",
  "Create an ethereal dreamlike quality",
  "Add apocalyptic wasteland atmosphere",
  "Make it feel nostalgic and sentimental",
  "Add horror movie atmosphere",
  "Create a peaceful zen garden vibe",
  "Make it feel chaotic and overwhelming",
  "Add romantic sunset lighting",
  "Create an eerie abandoned place mood",
  "Make it feel epic and heroic",
  "Add whimsical playful energy",
  "Create a gritty noir detective atmosphere",
  "Make it feel like a fever dream",
  "Add tropical vacation vibes",
  "Create a winter wonderland atmosphere",
  "Make it feel suspenseful and tense",

  // Seasonal & Time
  "Transform to look like autumn",
  "Add winter snow and frost",
  "Make it feel like spring blossoms",
  "Add summer beach vibes",
  "Make it look like sunset golden hour",
  "Transform to nighttime with stars",
  "Add rain and stormy weather",
  "Make it look like early morning mist",
  "Add Halloween spooky decorations",
  "Transform with Christmas holiday theme",

  // Artistic Movements & Famous Styles
  "Make it look like Van Gogh painted it",
  "Apply Andy Warhol pop art style",
  "Transform into Studio Ghibli animation",
  "Make it look like a Picasso cubist painting",
  "Add Salvador Dali surrealist elements",
  "Apply Monet impressionist style",
  "Make it look like Japanese ukiyo-e print",
  "Transform into art deco design",
  "Apply Banksy street art style",
  "Make it look like a Pixar movie scene",

  // Conversational Editing
  "Rotate the main subject 45 degrees",
  "Move the focus to the background",
  "Make the colors more vibrant and saturated",
  "Add something interesting in the corner",
  "Shift the perspective to a different angle",
  "Zoom in on the most interesting detail",
  "Add more contrast and punch",
  "Make the shadows deeper and richer",
  "Brighten up the highlights",
  "Add a vignette effect around the edges",
  "Make everything except the subject black and white",
  "Add lens flare from the side",
  "Tilt the horizon for dynamic composition",
  "Add motion blur to suggest movement",
  "Sharpen the details and textures",

  // Pop Culture & Trends
  "Make it look like a lo-fi hip hop thumbnail",
  "Add cottagecore aesthetic",
  "Transform into dark academia style",
  "Make it look like a K-pop music video",
  "Add Y2K cyber aesthetic",
  "Transform into vaporwave art",
  "Make it look like a Wes Anderson scene",
  "Add Studio 54 disco glamour",
  "Transform into steampunk style",
  "Make it look like a noir film still",

  // Environmental Changes
  "Place it in a mystical forest",
  "Add it to a bustling city street",
  "Transport to an alien planet",
  "Place in a gothic castle",
  "Add to a sunny beach paradise",
  "Move to a mountain summit",
  "Place in a cyberpunk megacity",
  "Transport to ancient ruins",
  "Add to a cozy coffee shop",
  "Place in the clouds above",

  // Fun & Playful
  "Add googly eyes to everything",
  "Make it look impossibly tiny",
  "Transform into a collectible trading card",
  "Add rubber duck in an unexpected place",
  "Make everything shiny and chrome",
  "Add laser eyes effect",
  "Transform into a motivational poster",
  "Make it look cursed",
  "Add chaotic maximalist decorations",
  "Turn it into a Where's Waldo scene",
];
